# Generated by Django 4.1.6 on 2023-02-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_pages_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
