# Generated by Django 4.1.6 on 2023-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_country_book_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
