# Generated by Django 4.1.6 on 2023-02-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_order_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='books.order'),
        ),
    ]
