# Generated by Django 4.1.6 on 2023-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_count_sold_alter_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='telegram_account_id',
            field=models.IntegerField(null=True),
        ),
    ]
